experiment:
  name: Multi_Condition_Screen
  control:
    name: Control
    replicates: 3
  conditions:
  - name: Condition1
    replicates: 3
  - name: Condition2
    replicates: 3
  - name: Condition3
    replicates: 3
  cell_types:
  - barcode: ATGCAGGG
    name: Keratinocyte
  - barcode: GTTGCAGC
    name: Fibroblast
  - barcode: ATAGCACG
    name: Endothelial
  library_config: default
